name: Robot Framework Test for Windows

on:
  # schedule:
    # Runs daily for every 2 hours
    # - cron: '0 */2 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-robot-tests:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Robot Framework tests
      run: |
        export PYTHONPATH=$PWD
        cd Test
        robot --pythonpath . cara.robot
